---
- name: Get show running-config of Cisco device
  hosts: all
  gather_facts: yes
  tasks:
    - name: Backup current switch config (ios)
      cisco.iosxr.iosxr_config:
        backup: yes
      register: backup_ios_location
